### ISSUE TITLE
[Issue] Pileup errors when using somatic mode 

### ISSUE THREAD

**Issue by njspix** [huishenlab/biscuit#16]
**Describe the bug**
Pileup seems to crash midway through writing a vcf file, resulting in truncated files. 

**BISCUIT version**
```
BISCUIT Version: 1.0.0

Using:
	htslib version: zwdzwd/htslib at commit f29fa32
	klib   version: zwdzwd/klib   at commit ca862f8
	sgsl   version: zwdzwd/sgsl   at commit a0ddc77
	utils  version: zwdzwd/utils  at commit 332459b

Libraries found at: https://github.com/huishenlab/biscuit/tree/master/lib
```

**Minimally Reproducible Example**
1. Reference genome:
`/varidata/research/projects/laird/nathan/resources/genome_data/grch38/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa`
2. Small dataset can be found in `/varidata/research/projects/laird/nathan/pileup_error`
2. Command(s) run
`biscuit pileup -g chr12:133260000-133275309 -S -T test.bam -I /varidata/research/projects/laird/nathan/projects/thesis_proper/CRC-003/bulk_wgs/results/Preprocessing/C3B1A/Recalibrated/C3B1A.recal.bam /varidata/research/projects/laird/nathan/resources/genome_data/grch38/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa`
3. Error given
`[refcache_getbase:165] Error retrieving base 133275310 outside range chr12:133258900-133275309.`

**Expected behavior**
No error should occur...

**Computer Resources**
VAI HPC

**Comment by jamorrison** [comment]
The issue was due to the chromosomes being in a different order between the two BAMs (they were aligned with references that were in a different sort order). However, the order of the chromosomes matters when comparing positions between the two BAMs. The best solution is to realign one of them with the same reference as the other and then rerun `biscuit pileup`.

**Comment by jamorrison** [comment]
For more background, this issue was caused by two samples being aligned to two different hg38 references (say, hg38 with contigs and hg38 without). BISCUIT can handle files that were aligned with different references, as long as the chromosomes are in the same order. Note, this isn't necessarily best practice as it may affect your results, but it is possible and can be done with some thought put in to what is being looked at and the potential effects on your results. That said, the order of the chromosomes in the references differed in this instance (see below for an example). Because the order differed, `biscuit pileup` was trying to retrieve reads from different chromosomes while running. (In this specific case, it was happening when running in somatic mode, but this issue also crops up when running a joint `pileup` with multiple BAMs being used as input to `pileup`.) Because different chromosomes were being compared (say, chromosome 12 versus chromosome 5), one of the reads was running past the end of the chromosome, causing the above issue.

*Reference 1 order:*
  - chr1
  - chr10
  - chr11
  - chr12
  - ...

*Reference 2 order:*
  - chr1
  - chr2
  - chr3
  - chr4
  - ...

**Comment by njspix** [comment]
Great, thank you so much for your help!
