### ISSUE TITLE
Trimming reads & comparison to bwa-meth / bismark?

### ISSUE THREAD

**Issue by semenko** [huishenlab/biscuit#27]
Hey team -- thanks for this great software!

We're experimenting with using this for methylation calls on EM-seq data (not using any of the variant calling features), and considering **bismark** and **bwa-meth** as well.

1. Do you have any recommendations for read trimming before alignment? (I saw this referenced in your Snakemake pipeline -- do you find read trimming important -- outside of say the Swift kit where the start of R2 is clearly biased?)

2. Do you have any head-to-head comparisons of Biscuit with bwa-meth, etc.?

Thanks!

**Comment by jamorrison** [comment]
Hi @semenko,

Sorry for the delay in responding! Below are some answers to your questions.

  1. For trimming, we [recently published a paper](https://doi.org/10.1186/s13072-021-00401-y) where we compared different library prep kits (including EM-seq) and make suggestions for trimming. A few other tips that I've noticed while working with biscuit:

  a. Generally, trimming is more dependent on the library preparation quality, rather than the aligner used.
  b. Don't rely on soft clipping to handle barcodes or indexes. It's best to trim these off prior to alignment.
  c. Generally, random primers are unmethylated, so leaving them on is possible during alignment, but it's suggested adjusting the `-5` option in `biscuit pileup` to account for this so as to not skew the calculated beta values.

  2. We currently are in the process of completing head-to-head comparisons with bwa-meth, so we don't have any results for that one yet. As for bismark, we found that biscuit was both faster in end-to-end time and aligned more high quality reads than bismark (across human, mouse, and zebrafish and for normal and diseased tissue). If your group does single-cell as well, we found that biscuit could handle paired-end reads natively, whereas bismark usually requires aligning the two reads separately and combining the BAMs downstream.
