### ISSUE TITLE
compatiblity with SNPsplit or whatshap

### ISSUE THREAD

**Issue by xixueyu96** [huishenlab/biscuit#43]
Please fill in as much as possible. The more information provided, the more likely we are to be able to help.

**Expected behavior**
I've heard that BISUIT can greatly increase the mapping ratio of methylation data. It's really cool! But my reads are intended to be haplo-tagged. Previously, I aligned my reads by bismark and haplo-tagged them by SNPsplit. I am worried that the BISUIT may not be compatible with popular haplo-tagging softwares, such as SNPsplit and whatshap. If it's compatible, please tell me. If it's not currently, is there any plan for you to supplement this function? Hope this issue find you well~ Looking forward for your response~

**BISCUIT version**
Version: v1.2.1

**Comment by jamorrison** [comment]
Hi @xixueyu96,

I'll start by saying that I'm not too familiar with the various haplo-tagging tools available, but I'll try helping as best I can. As an overall answer, I think BISCUIT is theoretically compatible with haplo-tagging tools, depending on how they go about phasing (see below for comments on SNPsplit and WhatsHap specifically).

Because SNPsplit replaces SNVs with `N`'s in the reference before aligning, BISCUIT won't work with SNPsplit. This is due to how the underlying `bwa mem`-based algorithm handles `N`'s in the reference during indexing and alignment. As for future compatibility, I don't foresee this incompatibility being resolved any time soon as it would require overhauling how `N`'s in the reference are handled by BISCUIT.

On the other hand, since WhatsHap uses already aligned BAMs, I think a BAM aligned by BISCUIT would work as input (assuming you've properly set up the metadata needed). I'm not sure how well it will work, but I think it's at least possible to use BISCUIT with WhatsHap.

Therefore, if you want to haplo-tag your reads, I would suggest trying WhatsHap.

**Comment by xixueyu96** [comment]
Hi @jamorrison ,

Thank you so much for your prompt and detailed response. I sincerely apologize for just now getting a chance to review your comment.

As you said, theoretically, Whatshap seems to be a closer fit compared to SNPsplit. Unfortunately, it appears that Whatshap may not have functions specifically designed for methylation data, especially data involving bisulfite conversion.

Despite this setback, I believe I can find alternative methods to integrate BISCUIT into my workflow. If you have any plan to add some functions for haplo-tagging to BISCUIT, please let me know and it would be immensely appreciated. 

Thanks again and I'll close this issue.
