### ISSUE TITLE
`BISCUIT` output

### ISSUE THREAD

**Issue by bounlu** [huishenlab/biscuit#44]
Hi,

I am trying to understand VCF fields in the BISCUIT output from `vcf2bed`. For example, I query somatic mutations to get `DP`,  `SP`,  `AC` and `AF1` fields for my `Tumor` and `Normal` samples as below:

`bcftools query -H -i 'SS=="2"' -f '%CHROM\t%POS\t%ID\t%REF\t%ALT\t%QUAL[\t%DP\t%SP\t%AC\t%AF1]' my_sample.snp.vcf | awk '{if ($7 != $9) print}' | head | column -t`

```
#[1]CHROM  [2]POS  [3]ID  [4]REF  [5]ALT  [6]QUAL  [7]DP  [8]SP   [9]AC  [10]AF1  [11]DP  [12]SP  [13]AC  [14]AF1
chr1       792779  .      C       T       5        4      T3Y1    3      1        1       C1      1       0
chr1       822354  .      C       T       0        3      T2Y1    2      1        0       .       0       .
chr1       826431  .      G       A       0        3      A2      2      1        0       .       0       .
chr1       851755  .      A       G       0        5      G3R2    3      1        1       R1      0       .
chr1       864003  .      G       N       5        4      Y3      3      1        1       G1      1       0
chr1       896732  .      T       C       0        4      C3Y1    3      1        0       .       0       .
chr1       915400  .      C       T       5        5      C1T2Y2  3      0.67     7       C1Y4    1       0
chr1       916657  .      G       A       9        10     G2A3R5  5      0.6      8       G3R4    3       0
chr1       924533  .      A       G       0        3      G2R1    2      1        2       R2      0       .
```

In the above list, how is the `AF1` field is calculated as **0.6** for the first sample on the 9.th line?

Why are the `Y` and `R` counts are ignored for the `AF1` calculation?

**Comment by jamorrison** [comment]
Short answer:

`Y` and `R` are not included in the `AF1` calculation when there is ambiguity in where they should be distributed. To use the 9th line as an example, since the REF base is an `G` and the ALT is a `A`, BISCUIT is unable to determine whether any `A`'s that occur on the OB/CTOB strand are due to the presence of the SNP or cytosine conversion. Therefore, `AF1` will be calculated on the unambiguous evidence (3 `A`'s and 2 `G`'s).

Long answer:

First, a description of ambiguous bases and how they're redistributed. Ambiguity arises when calling SNPs due to the cytosine conversion that occurs in WGBS. For reads on the OT/CTOT strand, C&rarr;T conversions can't be distinguished between being a SNP or an unmethylated cytosine. For reads on the OB/CTOB strand, G&rarr;A conversions can't be distinguished. Because of this, BISCUIT marks any occurrences of `T` on the OT/CTOT strand as the ambiguous `Y` and any `A`'s on the OB/CTOB strand as `R`. BISCUIT then tries to redistribute the ambiguous bases in the following manner (shown for C&rarr;T, but similar process for G&rarr;A):

1. When unambiguous evidence (either from the OB/CTOB strand or by observing an unconverted base) supporting the presence of one base (C or T) is present, BISCUIT adds the `Y` allele support to the support of that base.
2. When unambiguous evidence supporting *both* `C` and `T` is seen, then BISCUIT ignores the `Y` allele support.
3. When the reference is not a `C` or a `T` and unambiguous evidence is missing for both `C` and `T`, then the `Y` allele support is also ignored.
4. When the reference is a `C` or a `T` and unambiguous evidence is missing for both `C` and `T`, then the `Y` allele support is added to the reference allele support.

In other words, BISCUIT redistributes the allele support when unambiguous evidence supports one base or the other, or when the reference could explain the ambiguity if direct evidence is not present. Once the allele support has been redistributed, the SNP allele frequency `AF1` is calculated using the redistributed support.

For your example in the 9th row, two `G`'s come from either the OT/CTOT strand or represent methylated cytosines from the OB/CTOB strand, three `A`'s come from the OT/CTOT strand, and five `A`'s come from the OB/CTOB strand (given by `R`). Because the reference is a `G`, BISCUIT does not redistribute these `R`'s as it's ambiguous whether these are coming from the `A` SNP or an unmethylated cytosine. This leaves only 5 bases for calculating `AF1`: `3 / 5 = 0.6`.

I'll finish with a few definitions of the tags you mentioned based on what I just described.
- `DP`: Number of reads, regardless of bisulfite strand (OT/CTOT or OB/CTOB), that cover the locus in question.
- `SP`: Number of reads for each allele seen during pileup. Ambiguous bases (`T` for OT/CTOT and `A` for OB/CTOB) are given by the corresponding IUPAC ambiguous base (`Y` for OT/CTOT and `R` for OB/CTOB). This string is determined before ambiguous base redistribution occurs.
- `AC`: Depth used in calculating allele frequency. This number is based on the redistributed read counts (see above for redistribution process). If only ambiguous bases exist after redistribution, this value is `0`.
- `AF1`: ALT allele frequency calculated based on `AC` after allele support redistribution. If `AC = 0`, then `AF1 = .`.

**Comment by bounlu** [comment]
Thanks a lot for the detailed explanation. It's very useful and clear now.
