### ISSUE TITLE
Run biscuit epiread with customized snp BED files

### ISSUE THREAD

**Issue by JiantaoShi** [huishenlab/biscuit#45]
I am inquiring whether biscuit epiread supports utilizing a customized SNP BED file as input, rather than reporting a software bug. Using a customized file could be useful in several situations: (1) Matched DNA-seq data enables more accurate SNP calling. (2) Analysis may focus on specific pre-defined SNPs such as those in dbSNP. The default biscuit SNP BED file contains multiple columns. Would a customized BED with only the first 5 columns (chr, start, end, ref, alt) be compatible? 

<img width="542" alt="2023-11-24 16 23 41" src="https://github.com/huishenlab/biscuit/assets/5055792/5f15b8bc-862a-4b1e-af79-be36f6078422">

**Comment by jamorrison** [comment]
The VAF is used to determine if methylation can reasonably be called simultaneously with a C&rarr;T (or G&rarr;A) SNP. This occurs if `VAF < 0.05` in instances where REF is `C` (or `G`) and ALT is `T` (or `A`).

For your specific example, I would expect larger differences due to differences in the called SNPs (dbSNP vs BISCUIT) over the additional methylation. This is because most SNPs will have a VAF over `0.05` (either due to lower coverage or low likelihood of having rare SNPs), so in most instances methylation won't be called in the ambiguous cases (e.g., `C`&rarr;`T`). That said, the scale of the differences would likely vary from dataset to dataset and how closely the SNP positions in your BED file align with those called from BISCUIT.

**Comment by JiantaoShi** [comment]
Thanks, that helps a lot!
