### ISSUE TITLE
weird rectangle output

### ISSUE THREAD

**Issue by weishwu** [huishenlab/biscuit#8]
If I run rectangle directly on my epiread it says: "**[main_rectangle:79] Error, rectangle cannot cross chromosomes**". The manual does not say the input has to be chromosome split.
If I run it on a subset of the epiread in chr1, it finishes but the output looks weird. The output simply appends a 9th column to the epiread file and the 9th column is a string of 1,020,893 Ns.

My epiread input:
```
1	K00135:125:HFV57BBXX:1:1223:20618:2404	2	-	39154135	C	.	.
1	K00135:125:HFV57BBXX:1:1223:20618:2404	1	-	39154135	C	.	.
1	K00135:125:HFV57BBXX:3:2211:8044:44482	1	+	47760131	C	.	.
1	K00135:125:HFV57BBXX:1:2212:23673:26898	1	-	61731684	CCC	.	.
1	K00135:125:HFV57BBXX:1:2212:23673:26898	2	-	61731684	CCC	.	.
1	K00135:125:HFV57BBXX:1:2109:1702:26318	1	-	69191536	TTTCCCC	.	.
1	K00135:125:HFV57BBXX:3:1109:11759:18599	2	-	173991209	C	.	.
1	K00135:125:HFV57BBXX:3:1109:11759:18599	1	-	173991209	C	.	.
```

My rectangle command-line:
```
biscuit_0_3_16_linux_amd64 rectangle -o epiread_rslM1Li_chr1_epiread_matrix Mus_musculus.GRCm38.dna_sm.primary_assembly.fa epiread_rslM1Li_chr1.epiread
```

**Comment by jamorrison** [comment]
Hi @weishwu,

`rectangle` only works on epiread files with individual chromosomes in them. I have updated the User's Guide Epiread page to reflect this.

As for the `rectangle` output, your result is to be expected based on the input you provided. Each C/T/N in the string found in the 9th column represents one CpG found between the start position (chr1:39154135, in your case) and the end position (chr1:173991209), where:

- C = methylated cytosine in read,
- T = unmethylated cytosine in read, and
- N = unknown CpG methylation status.

Therefore, the string length in the 9th column will increase as you increase the distance between the start and end positions.

**Comment by weishwu** [comment]
Thanks @jamorrison for the explanation. I have some follow-up questions:
1. Does each string only incorporate the CpG status revealed by that read?
2. I have directional library. Do the strings distinguish the two strands? 
3. Does the string include SNPs?
4. Does the string always start from the position of the first read and end with the last read (assuming coord-sorted)? Sorry if I'm asking naive questions because I simply don't understand what's the purpose of "rectangle".
5. What's the input to 'biscuit asm'? The command-lines in the manual are:
```
$ sort -k1,1 -k2,2n -k3,3n my_epiread_file.epiread > my_output.epiread
$ biscuit asm my_output.epiread > my_output.asm
```
However, this seems to suggest a different format of the epiread. I guess "-k2,2n -k3,3n" suggests the 2nd and the 3rd positions should be numeric, but the 2nd position in the epiread is the read name.

**Comment by jamorrison** [comment]
To answer your questions:

1. **_Does each string only incorporate the CpG status revealed by that read?_** Correct, any CpGs not in that read are denoted by a "N."
2. **_I have directional libraries. Do the strings distinguish the two strands?_** No, but column 4 can be used to distinguish between the two strands.
3. **_Does the string include SNPs?_** No, only CpGs are included in the string.
4. **_Does the string always start from the position of the first read and end with the last read (assuming coord-sorted)? Sorry if I'm asking naive questions because I simply don't understand what's the purpose of `rectangle`._** To the question, yes, the string begins from the first read position and ends with the last read position (assuming coordinate sorting). The `rectangle` command is used to form matrix-like data for visualizing epireads.
5. **_What's the input to `biscuit asm`?_** The input is a read sorted epiread file (the file is coordinate sorted by default). The `-k2,2n` was a typo in the documentation, which I corrected (now is `-k2,2`). Thanks for pointing that out!

**Comment by jamorrison** [comment]
Hi @weishwu,

I have to correct myself on my response to question 5. The input to `biscuit asm` is a coordinate-sorted epiread file that was generated by running `biscuit epiread` in pairwise mode (i.e. with the `-P` flag). See the updated allele-specific methylation documentation page (https://huishenlab.github.io/biscuit/docs/allele_meth.html) for more details.
